# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'declare_commands.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(265, 179)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(20, 20, 223, 141))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_command = QtWidgets.QLabel(self.splitter)
        self.label_command.setObjectName("label_command")
        self.lineEdit_command = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_command.setObjectName("lineEdit_command")
        self.pushButton_validate_command = QtWidgets.QPushButton(self.splitter)
        self.pushButton_validate_command.setObjectName("pushButton_validate_command")
        self.pushButton_disable_commande = QtWidgets.QPushButton(self.splitter)
        self.pushButton_disable_commande.setObjectName("pushButton_disable_commande")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_command.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Commande pour faire une acquisition :</span></p></body></html>"))
        self.pushButton_validate_command.setText(_translate("Dialog", "Valider la commande"))
        self.pushButton_disable_commande.setText(_translate("Dialog", "Pas de Commande"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
