# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Help_app_temp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Help(object):
    def setupUi(self, Help):
        Help.setObjectName("Help")
        Help.resize(468, 485)
        self.label_guide = QtWidgets.QLabel(Help)
        self.label_guide.setGeometry(QtCore.QRect(20, 10, 431, 431))
        self.label_guide.setObjectName("label_guide")

        self.retranslateUi(Help)
        QtCore.QMetaObject.connectSlotsByName(Help)

    def retranslateUi(self, Help):
        _translate = QtCore.QCoreApplication.translate
        Help.setWindowTitle(_translate("Help", "Guide d\'utilisation"))
        self.label_guide.setText(_translate("Help", "<html><head/><body><p>En premier lieu, vous devez éditer la commande qui ordonne à votre appareil de faire</p><p>une acquisition en cliquant sur le bouton<span style=\" font-style:italic;\"> Edit Commands</span></p><p>(par défaut le programme considère qu\'il n\'y en a pas).</p><p><br/></p><p>Vous devez ensuite établir la connection série avec votre appareil en indiquant baudrate</p><p>, timeout et port virtuel.</p><p><br/></p><p>Vous pouvez changer la durée entre 2 mesures même pendant une acquisition.</p><p><br/></p><p>Si l\'acquisition ne se lance pas, re-appyuez sur le bouton ou relancez l\'application</p><p>(sans doute que le moment entre la déclaration de la commande et le</p><p>début de l\'acquisition est trop court). </p><p><br/></p><p>En activant l\'alarme, vous receverez un mail de vous même vous indiquant la date</p><p>à laquelle la température seuil a été franchie.</p><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Help = QtWidgets.QDialog()
    ui = Ui_Help()
    ui.setupUi(Help)
    Help.show()
    sys.exit(app.exec_())
