# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'params_scope.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(428, 358)
        self.splitter_11 = QtWidgets.QSplitter(Dialog)
        self.splitter_11.setGeometry(QtCore.QRect(30, 20, 371, 311))
        self.splitter_11.setOrientation(QtCore.Qt.Vertical)
        self.splitter_11.setObjectName("splitter_11")
        self.splitter_10 = QtWidgets.QSplitter(self.splitter_11)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.label_params_oscillo = QtWidgets.QLabel(self.splitter_10)
        self.label_params_oscillo.setObjectName("label_params_oscillo")
        self.pushButton = QtWidgets.QPushButton(self.splitter_10)
        self.pushButton.setObjectName("pushButton")
        self.splitter = QtWidgets.QSplitter(self.splitter_11)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_bd_rate = QtWidgets.QLabel(self.splitter)
        self.label_bd_rate.setObjectName("label_bd_rate")
        self.lineEdit_baud_rate = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_baud_rate.setObjectName("lineEdit_baud_rate")
        self.splitter_9 = QtWidgets.QSplitter(self.splitter_11)
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.label_hscale = QtWidgets.QLabel(self.splitter_9)
        self.label_hscale.setObjectName("label_hscale")
        self.lineEdit_hscale = QtWidgets.QLineEdit(self.splitter_9)
        self.lineEdit_hscale.setObjectName("lineEdit_hscale")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_11)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_hoffset = QtWidgets.QLabel(self.splitter_2)
        self.label_hoffset.setObjectName("label_hoffset")
        self.lineEdit_hoffset = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEdit_hoffset.setObjectName("lineEdit_hoffset")
        self.splitter_8 = QtWidgets.QSplitter(self.splitter_11)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.label_vscaleCH1 = QtWidgets.QLabel(self.splitter_8)
        self.label_vscaleCH1.setObjectName("label_vscaleCH1")
        self.lineEdit_vscaleCH1 = QtWidgets.QLineEdit(self.splitter_8)
        self.lineEdit_vscaleCH1.setObjectName("lineEdit_vscaleCH1")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_11)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.label_vscaleCH2 = QtWidgets.QLabel(self.splitter_7)
        self.label_vscaleCH2.setObjectName("label_vscaleCH2")
        self.lineEdit_vscaleCH2 = QtWidgets.QLineEdit(self.splitter_7)
        self.lineEdit_vscaleCH2.setObjectName("lineEdit_vscaleCH2")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_11)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.labe_offsetCH1_V = QtWidgets.QLabel(self.splitter_6)
        self.labe_offsetCH1_V.setObjectName("labe_offsetCH1_V")
        self.lineEdit_offsetCH1_V = QtWidgets.QLineEdit(self.splitter_6)
        self.lineEdit_offsetCH1_V.setObjectName("lineEdit_offsetCH1_V")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_11)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_offsetCH2_V = QtWidgets.QLabel(self.splitter_5)
        self.label_offsetCH2_V.setObjectName("label_offsetCH2_V")
        self.lineEdit_offsetCH2_V = QtWidgets.QLineEdit(self.splitter_5)
        self.lineEdit_offsetCH2_V.setObjectName("lineEdit_offsetCH2_V")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_11)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_offsetCH1_V = QtWidgets.QLabel(self.splitter_4)
        self.label_offsetCH1_V.setObjectName("label_offsetCH1_V")
        self.lineEdit_offsetCH1_div = QtWidgets.QLineEdit(self.splitter_4)
        self.lineEdit_offsetCH1_div.setObjectName("lineEdit_offsetCH1_div")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_11)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_offsetCH2_div = QtWidgets.QLabel(self.splitter_3)
        self.label_offsetCH2_div.setObjectName("label_offsetCH2_div")
        self.lineEdit_offsetCH2_div = QtWidgets.QLineEdit(self.splitter_3)
        self.lineEdit_offsetCH2_div.setObjectName("lineEdit_offsetCH2_div")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Paramètres de l\'oscilloscope"))
        self.label_params_oscillo.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Paramètres Oscilloscope :</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Valider les paramètres"))
        self.label_bd_rate.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Baud rate :</span></p></body></html>"))
        self.label_hscale.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Horizontal Scale (en s) :</span></p></body></html>"))
        self.label_hoffset.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Horizontal offset (en s) :</span></p></body></html>"))
        self.label_vscaleCH1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Vertical Scale CH1 (en V) :</span></p></body></html>"))
        self.label_vscaleCH2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Vertical Scale CH2 (en V) :</span></p></body></html>"))
        self.labe_offsetCH1_V.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Offset CH1 (en V) :</span></p></body></html>"))
        self.label_offsetCH2_V.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Offset CH2 (en V) :</span></p></body></html>"))
        self.label_offsetCH1_V.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Offset CH1 (en div) :</span></p></body></html>"))
        self.label_offsetCH2_div.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Offset CH2 (en div) :</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
